" DISPLAY OPTIONS ----------

" Display line numbers
set number

" Enable line wrapping
set wrap

" Always display the status bar
set laststatus=2

" INDENTATION OPTIONS ----------

" Autoindent (new lines inherit the indentation of previous lines)
set autoindent

" Indent using 2 spaces
set tabstop=2

" When shifting, use 2 spaces
set shiftwidth=2

" CONFIG OPTIONS ----------

" Auto-install vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
